version: "3.9"
services:
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - mongodb_config:/data/configdb
    env_file:
      - .env
  redis:
    container_name: "redis"
    image: redis:alpine
    ports: 
      - "6379:6379"
    volumes:
      - redis-data:/data
    env_file:
      - .env
  web:
    build: .
    container_name: "0auth"
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    restart: "always"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
volumes:
  mongodata:
  mongodb_config:
  redis-data:
    driver: local